version: "3"
services:
  rabbit1:
    image: rabbitmq:3.6.1-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "test_cluster"
    ports:
      - "4369"
      - "5672"
      - "15672"
  rabbit2:
    image: rabbitmq:3.6.1-management
    hostname: rabbit2
    environment:
      RABBITMQ_ERLANG_COOKIE: "test_cluster"
    ports:
      - "4369"
      - "5672"
      - "15672"
  rabbit3:
    image: rabbitmq:3.6.1-management
    hostname: rabbit3
    environment:
      RABBITMQ_ERLANG_COOKIE: "test_cluster"
    ports:
      - "4369"
      - "5672"
      - "15672"
  rabbit4:
    image: rabbitmq:3.6.1-management
    hostname: rabbit4
    environment:
      RABBITMQ_ERLANG_COOKIE: "test_cluster"
    ports:
      - "4369"
      - "5672"
      - "15672"

